apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - name: squid
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
        ports:
        - containerPort: 3128
          name: squid
          protocol: TCP
        volumeMounts:
        - name: squid-config-volume
          mountPath: /etc/squid/squid.conf
          subPath: squid.conf
        - name: squid-data
          mountPath: /var/spool/squid
      volumes:
      - name: squid-config-volume
        configMap:
          name: "{{ .Release.Name }}-config"
          items:
          - key: squid.conf
            path: squid.conf
      - name: squid-data
        emptyDir: {}
        # persistentVolumeClaim:
        #   claimName: "{{ .Release.Name }}-pvc"