---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  labels:
    app.kubernetes.io/instance: {{ .Values.appLabels.app }}
spec:
  ports:
  - port: 3128
  selector:
    app.kubernetes.io/instance: {{ .Values.appLabels.app }}